name: internet_connection_checker
description: A pure Dart library that checks for internet by opening a socket to
  a list of specified addresses, each with individual port and timeout. Defaults
  are provided for convenience.
version: 0.0.1+2
repository: https://github.com/RounakTadvi/internet_connection_checker
homepage: https://github.com/RounakTadvi/internet_connection_checker/tree/main

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.17.10
  very_good_analysis: ^2.1.2
  coverage: ^1.0.3
